name = "orca"
main = "src/index.ts"
compatibility_date = "2022-05-11"

[triggers]
# crons = ["0 13 * * *"]
crons = ["*/1 * * * *"]

[dev]
port = 8080

[env.development]
kv_namespaces = [
    { binding = "KV_TOKEN_LIST_DEV", preview_id = "db0634b590964ba29ad7b149e2245538", id = "db0634b590964ba29ad7b149e2245538" }
]

[env.production]
# account_id = "PROD_ACCOUNT_ID || CLOUDFLARE_ACCOUNT_ID on CI"
name = "orca-cloudflare"
vars = { ENVIRONMENT = "production",  ORCA_ENDPOINT = "https://api.orca.so/configs" }
kv_namespaces = [{ binding = "KV_TOKEN_LIST_PROD", id = "c07b6685d01a444a99d2a8dba00a5911" }]
