name = "orca"
main = "src/index.ts"
compatibility_date = "2022-05-11"

[triggers]
crons = ["0 13 * * *"]

[env.development]
account_id = "YOUR_DEV_ACCOUNT_ID"
name = "orca-cloudflare-proxy-development"
vars = { ENVIRONMENT = "development",  ORCA_ENDPOINT = "https://api.orca.so/configs" }
kv_namespaces = [{ binding = "YOUR_DEV_BINDING_NAME", preview_id = "SAME_AS_ID", id = "YOUR_BINDING_ID" }]

[env.production]
account_id = "YOUR_PROD_ACCOUNT_ID"
name = "orca-cloudflare"
vars = { ENVIRONMENT = "production",  ORCA_ENDPOINT = "https://api.orca.so/configs" }
kv_namespaces = [{ binding = "YOUR_PROD_BINDING_NAME", id = "PROD_ID" }]


