name: Version Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --all --tags

      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: package.json
          tagFormat: v${version}
        id: version_check_staging
#name: Bump version
#
#on:
#  pull_request:
#    types:
#      - opened
#      - synchronize
#
#jobs:
#  version_bump:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Automated Version Bump
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT_ORCA_PROXY_BOT }}
#          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
#          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
#          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
#          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
#        run: |
#          echo ${{ github.ref_name }}
#          echo ${{ github.ref }}
#          echo origin/${{ github.event.pull_request.head.ref }}
#          yarn version --patch --no-commit-hooks --no-git-tag-version
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          branch: ${{ github.event.pull_request.head.ref }}
#          force: true
