name: Bump version

on:
  push:

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        with:
          skip-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-deploy:
    uses: ./.github/workflows/deploy-worker.yml
