name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint_es:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Run ESLint

    steps:
      - uses: actions/checkout@v3

      - name: install dependecies
        run: yarn install

      - name: lint ES
        run: yarn lint:es

  lint_type:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Run TS Typecheck
    needs: lint_es

    steps:
      - uses: actions/checkout@v3

      - name: install dependecies
        run: yarn install

      - name: type-checking TS
        run: yarn lint:type

  test_unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Run Jest
    needs: lint_type

    steps:
      - uses: actions/checkout@v3

      - name: install dependecies
        run: yarn install

      - name: run unit tests
        run: yarn jest
